Restart the job during initialization if termination was requested [CTT-1034] (#6072)
```
2026-02-24 14:11:33,353 [ERROR] [ForkJoinPool.commonPool-worker-3] [c.h.j.i.EnterpriseMasterContext]: [172.18.0.3]:5702 [DedupPipelineGracefulChaosTest] [5.7.0-SNAPSHOT] Exception during callback
java.lang.AssertionError: mode is null
	at com.hazelcast.jet.impl.MasterJobContext.lambda$getErrorFromResponses$17(MasterJobContext.java:707) ~[hazelcast-enterprise-5.7.0-SNAPSHOT.jar:5.7.0-SNAPSHOT]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.hazelcast.jet.impl.MasterJobContext.getErrorFromResponses(MasterJobContext.java:707) ~[hazelcast-enterprise-5.7.0-SNAPSHOT.jar:5.7.0-SNAPSHOT]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$invokeStartExecution$13(MasterJobContext.java:632) ~[hazelcast-enterprise-5.7.0-SNAPSHOT.jar:5.7.0-SNAPSHOT]
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipant
```

Explanation:

There is a race condition when a job is being initialized and a
termination request with restart is received at the same time.

Flow:
• A termination request is received. It sets the terminationRequest
variable, sends termination to all members, and waits for the job to
finish.
• During job initialization, the code checks terminationRequest, ignores
it (as restart is requested), clears it, and proceeds to start the job.
• The job then stops (because termination was already sent to all
members), and finalization is performed. Since terminationRequest was
cleared receive assertion exception.

Solution:
Do not ignore a termination request with restart during job
initialization. If a termination request is present, stop the
initialization process and reschedule the job restart using the standard
restart flow (the same as if the job were already running).

------------

- __Fixes:__ https://hazelcast.atlassian.net/browse/CTT-1034
- __Backport of:__        NONE
- __Jira Ticket:__ https://hazelcast.atlassian.net/browse/CTT-1034
- __TDD:__ NONE
- __ADR:__ NONE
- __Protocol Changes:__  NONE

------------

__Checklist:__

- [x] __Breaking Changes:__ I have described any breaking changes on
behavioral change to Public API, protocol, serialization, or snapshot
and the migration path if applicable.
- [x] __Traceability:__ I have associated the PR with a Jira ticket
through title and linked relevant design docs (ADR/TDD).
- [x] __Correctness & Concurrency:__ I have verified the logic for
thread safety, race conditions, and distributed system impacts.
- [x] __Testing:__ I have included meaningful tests. New public APIs
have 100% coverage.
- [x] __Public Config API:__ I have followed the
[Checklist](https://github.com/hazelcast/hazelcast/wiki/Checklist-for-Hazelcast-config-changes)
for Hazelcast config changes.
- [x] __Performance:__ I have checked for unnecessary performance hits
(e.g., excessive object creation).
- [x] __Clarity:__ The code is written with empathy for the "next
engineer" and includes comments for complex "why" logic.
- [x] __Public API Standards:__ New APIs have @Nonnull/@Nullable
annotations and @since, @returns, @throws Javadoc tags.
- [x] __Labels & Metadata:__ All labels (`Type`, `Source`, `Module`) and
`Milestone` are set; release note labels are applied.
- [x] __Cross-Language:__ Label `All Languages Should Check` is set if
Java client API changes affect non-Java clients.

GitOrigin-RevId: a925617005d2ce9d2db3a5b3f2cfc03f7788e0a2