Fix com.hazelcast.xa.HazelcastXATest.testParallel [HZ-1763]
- Increased the waiting time of threads to 30 seconds and changed logic. We are waiting for executorService to finish tasks before verification. This is necessary because when the test fails, since the threads are still running I see lots of messages (53 exactly in this case) like below

"03:36:22,150 ERROR |testParallel| - [HazelcastXATest] pool-20200-thread-1 - Exception during txn
java.lang.IllegalStateException: Server is shutting down..."

The threads are still running and this makes the output unreadable. With this change, we will make sure that if the executorservice could not finish, we will know the test failure reason clearly.

gh : https://github.com/hazelcast/hazelcast/issues/21429