Fixes testClientConnectionEvents
Issue seen in pr https://github.com/hazelcast/hazelcast/pull/9561
with following error message

	java.lang.AssertionError: LifecycleState failed
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:285)

Since client shutdown can happen before detecting cluster gone,
we need to wait disconected state before shutting down client.