[HZG-242] Fix windows test failure com.hazelcast.jet.enterprise.EEJobStatusListenerTest.testListener_suspendOnFailure (#3739)
Fix error on windows due to new lines and line endings.

expected:<[Jet: STARTING -> RUNNING, Jet: RUNNING -> SUSPENDED ( at
com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:289)),
User: SUSPENDED -> FAILED (Cancel)]> but was:<[Jet: STARTING -> RUNNING,
Jet: RUNNING -> SUSPENDED (com.hazelcast.jet.JetException: Exception in
ProcessorTasklet{0ca7-46a2-6489-0001/batchSource#1}:
com.hazelcast.jet.JetException: mock error), User: SUSPENDED -> FAILED
(Cancel)]>

Checklist:
- [X] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [X] Add `Add to Release Notes` label if changes should be mentioned in
release notes or `Not Release Notes content` if changes are not relevant
for release notes
- [ ] Architecture Design Record (ADR) reviewed and signed-off if this
PR represents a significant architectural change
- [X] Request reviewers if possible
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc
- [ ] Send backports/forwardports if fix needs to be applied to
past/future releases
GitOrigin-RevId: e5690e4cbbf694c39b35418d149f1adddd1ffcbf