Ensure now-optional `commons-codec` dependency is available for `testcontainers` usage (#894)
In https://github.com/hazelcast/hazelcast-mono/pull/841,
`commons-compress` was updated - now [declares the `codec` dependency as
optional](https://github.com/apache/commons-compress/pull/482).

But `testcontainers` expects an older version of `commons-compress`
where `commons-codec` was bundled, leading to:
```
java.lang.NoClassDefFoundError: org/apache/commons/codec/Charsets
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.<init>(TarArchiveOutputStream.java:212)
	{...}
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:333)
	at com.hazelcast.jet.cdc.DebeziumCdcIntegrationTest.mysql(DebeziumCdcIntegrationTest.java:78)
```

This adds back an explicit `commons-codec` for those scenarios.

Fixes https://github.com/hazelcast/hazelcast/issues/26264

GitOrigin-RevId: e611f82c6cd8afa5764d5ce415585a6a5085eb39