Do not try reconfigure Kafka Connect task runners if there are none (#24024)
Do not try reconfigure Kafka Connect task runners if there are none as
it ends with an error:

```
2023-03-20 16:03:54 INFO  CachedConnectionProvider:79 - Attempting to open connection #1 to MySql
2023-03-20 16:03:54 INFO  TableMonitorThread:82 - Starting thread to monitor tables.
2023-03-20 16:03:54 ERROR TableMonitorThread:224 - Encountered an unrecoverable error while reading tables from the database
java.lang.IllegalArgumentException: Number of groups must be positive.
	at org.apache.kafka.connect.util.ConnectorUtils.groupPartitions(ConnectorUtils.java:41) ~[connect-api-2.8.2.jar:?]
	at io.confluent.connect.jdbc.JdbcSourceConnector.taskConfigs(JdbcSourceConnector.java:180) ~[?:?]
	at com.hazelcast.jet.kafka.connect.impl.ConnectorWrapper.requestTaskReconfiguration(ConnectorWrapper.java:105) ~[classes/:?]
	at com.hazelcast.jet.kafka.connect.impl.ConnectorWrapper.access$100(ConnectorWrapper.java:37) ~[classes/:?]
	at com.hazelcast.jet.kafka.connect.impl.ConnectorWrapper$JetConnectorContext.requestTaskReconfiguration(ConnectorWrapper.java:94) ~[classes/:?]
	at io.confluent.connect.jdbc.source.TableMonitorThread.run(TableMonitorThread.java:86) [?:?]
Exception in thread "Thread-25" org.apache.kafka.connect.errors.ConnectException: Encountered an unrecoverable error while reading tables from the database
	at io.confluent.connect.jdbc.source.TableMonitorThread.fail(TableMonitorThread.java:226)
	at io.confluent.connect.jdbc.source.TableMonitorThread.run(TableMonitorThread.java:89)
Caused by: java.lang.IllegalArgumentException: Number of groups must be positive.
	at org.apache.kafka.connect.util.ConnectorUtils.groupPartitions(ConnectorUtils.java:41)
	at io.confluent.connect.jdbc.JdbcSourceConnector.taskConfigs(JdbcSourceConnector.java:180)
	at com.hazelcast.jet.kafka.connect.impl.ConnectorWrapper.requestTaskReconfiguration(ConnectorWrapper.java:105)
	at com.hazelcast.jet.kafka.connect.impl.ConnectorWrapper.access$100(ConnectorWrapper.java:37)
	at com.hazelcast.jet.kafka.connect.impl.ConnectorWrapper$JetConnectorContext.requestTaskReconfiguration(ConnectorWrapper.java:94)
	at io.confluent.connect.jdbc.source.TableMonitorThread.run(TableMonitorThread.java:86)
```

When `JetConnectorContext#requestTaskReconfiguration()` is called during
initialization, the taskRunners.size() is 0. When we pass 0 as the
argument to connector.taskConfigs() it is throwing this exception
It does not happen again after a runner has started. It happens only
during initialization

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [x] Send backports/forwardports if fix needs to be applied to
past/future releases
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc