ICache expiration tasks should be un-scheduled when cluster is PASSIVE (#13888)
IMap expiration tasks are already un-scheduled when cluster is PASSIVE
but this was missing for ICache tasks.

Otherwise following error log is printed periodically until cluster
changes to another state:

```
Cluster is in PASSIVE state! Operation: com.hazelcast.cache.impl.operation.CacheClearExpiredOperation{serviceName='hz:impl:cacheService',
identityHash=586485934, partitionId=80, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1,
callTimeout=9223372036854775807, expirationPercentage=10}
java.lang.IllegalStateException: Cluster is in PASSIVE state!
Operation: com.hazelcast.cache.impl.operation.CacheClearExpiredOperation{serviceName='hz:impl:cacheService', identityHash=586485934,
partitionId=80, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807,
expirationPercentage=10}
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.checkNodeState(OperationRunnerImpl.java:263) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:185) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) [classes/:?]
```