Mapping HazelcastInstanceNotActiveException exception to TopologyChange (#770)
https://hazelcast.atlassian.net/browse/HZ-2240

On coordinator convert HazelcastInstanceNotActiveException exception to
TopologyChangedException after receiving results from members.

considering only this stack trace:

```
2023-03-27 15:31:26,011 [ERROR] [hz.recursing_nash.cached.thread-13] [.h.j.i.o.SubmitJobOperation]: [129.40.130.38]:8802 [zdih-p15] [5.2.1] Execution on a member failed: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
com.hazelcast.jet.JetException: Execution on a member failed: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.jet.impl.LightMasterContext.findError(LightMasterContext.java:310) ~[hazelcast-enterprise-5.2.1-nlc.jar:5.2.1]
	...
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.jet.impl.JobExecutionService.failIfNotRunning(JobExecutionService.java:489) ~[hazelcast-enterprise-5.2.1-nlc.jar:5.2.1]
	at com.hazelcast.jet.impl.JobExecutionService.runLightJob(JobExecutionService.java:291) ~[hazelcast-enterprise-5.2.1-nlc.jar:5.2.1]

```

It happens if the non-coordinator member is shut.

After receiving the exceptional response, the coordinator notified all
members to cancel the job, including the member who was the exception's
source. Do we want to change this?

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Add `Add to Release Notes` label if changes should be mentioned in
release notes or `Not Release Notes content` if changes are not relevant
for release notes
- [x] Request reviewers if possible
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc
- [x] Send backports/forwardports if fix needs to be applied to
past/future releases

---------

Co-authored-by: Krzysztof Jamróz <krzysztof.jamroz@hazelcast.com>
Co-authored-by: Krzysztof Jamróz <79092062+k-jamroz@users.noreply.github.com>
GitOrigin-RevId: ecdd7c0afd1e44eb11f5692db10fdffee8421910