Downgrade AWS SDK to address HttpClient5 / Hadoop incompatibilities (#6948)
AWS uses a shaded copy of `Apache HttpClient 5` since
https://github.com/aws/aws-sdk-java-v2/issues/7007 - but Hadoop [uses
the shaded `HttpClient 4`
classes](https://github.com/apache/hadoop/blob/9d50c6884666e794e45102260a4017bb31802e1b/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/AWSClientConfig.java#L35).

Hence in the Docker tests fail with:
```
[INFO] Running com.hazelcast.jet.files.S3FilesTest
[ERROR] Tests run: 22, Failures: 3, Errors: 17, Skipped: 0, Time elapsed: 34.40 s <<< FAILURE! -- in com.hazelcast.jet.files.S3FilesTest
[ERROR] com.hazelcast.jet.files.S3FilesTest.shouldReadAllFilesInDirectory -- Time elapsed: 3.134 s <<< ERROR!
java.util.concurrent.CompletionException:
com.hazelcast.jet.JetException: java.lang.NoClassDefFoundError: software/amazon/awssdk/http/apache/ApacheHttpClient
	at org.apache.hadoop.fs.s3a.impl.AWSClientConfig.createHttpClientBuilder(AWSClientConfig.java:149)
	at org.apache.hadoop.fs.s3a.DefaultS3ClientFactory.createS3Client(DefaultS3ClientFactory.java:136)
	at org.apache.hadoop.fs.s3a.impl.ClientManagerImpl.lambda$createS3Client$0(ClientManagerImpl.java:137)
	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.invokeTrackingDuration(IOStatisticsBinding.java:546)
	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:527)
	at org.apache.hadoop.util.functional.LazyAtomicReference.eval(LazyAtomicReference.java:94)
	at org.apache.hadoop.util.functional.LazyAutoCloseableReference.eval(LazyAutoCloseableReference.java:54)
	at org.apache.hadoop.fs.s3a.impl.ClientManagerImpl.getOrCreateS3Client(ClientManagerImpl.java:178)
	at org.apache.hadoop.fs.s3a.impl.S3AStoreImpl.getOrCreateS3Client(S3AStoreImpl.java:340)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:823)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3615)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:172)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3716)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3667)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:557)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:366)
	at com.hazelcast.jet.hadoop.impl.HadoopFileSourceFactory.getInputPath(HadoopFileSourceFactory.java:182)
	at com.hazelcast.jet.hadoop.impl.HadoopFileSourceFactory$1.acceptEx(HadoopFileSourceFactory.java:147)
	at com.hazelcast.jet.hadoop.impl.HadoopFileSourceFactory$1.acceptEx(HadoopFileSourceFactory.java:129)
	at com.hazelcast.function.ThrowingConsumer.accept(ThrowingConsumer.java:56)
	at com.hazelcast.jet.hadoop.impl.ReadHadoopNewApiP$MetaSupplier.updateConfiguration(ReadHadoopNewApiP.java:218)
	at com.hazelcast.jet.hadoop.impl.ReadHadoopNewApiP$MetaSupplier.init(ReadHadoopNewApiP.java:190)
	at com.hazelcast.jet.impl.execution.init.ExecutionPlanBuilder.lambda$createExecutionPlans$6fa8fcfe$1(ExecutionPlanBuilder.java:171)
	at com.hazelcast.function.ThrowingRunnable.run(ThrowingRunnable.java:36)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:587)
	at com.hazelcast.jet.impl.execution.init.ExecutionPlanBuilder.lambda$createExecutionPlans$547c6d3f$1(ExecutionPlanBuilder.java:170)
	at com.hazelcast.function.ThrowingRunnable.run(ThrowingRunnable.java:36)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1825)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.PoolExecutorThreadFactory$ManagedThread.executeRun(PoolExecutorThreadFactory.java:89)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.http.apache.ApacheHttpClient
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 35 more
```

This is non-trivial to resolve - there is no explicit dependency we can
include to get the
`software.amazon.awssdk.thirdparty.org.apache.http.conn.socket.ConnectionSocketFactory`
class for example *.

Instead, downgraded to the last non-problematic AWS SDK and added a
`QuickTest` to block automated updates until it can be addressed.

* for the curious,
`software.amazon.awssdk.thirdparty.org.apache.http.conn.socket.ConnectionSocketFactory`
is a shaded as [part of the large 600MB `bundle`
dependency](https://github.com/aws/aws-sdk-java-v2/blob/776a0ccb0894c9b0e67f9fdb591bb6106ff21d08/bundle-sdk/pom.xml#L309-L315)
we've already deliberately avoided using eg in
https://github.com/hazelcast/hazelcast-mono/pull/2571. Additionally,
`HttpClient 4` depends on `HttpCore 4` which is
[EOL](https://hc.apache.org/httpcomponents-core-4.4.x/index.html).

GitOrigin-RevId: 643bd5a260c24bacfc920c77bebfceb3a3f9a29c