Fix HD entry processor missing entries when entries expire [HZG-479] (#4620)
The case described in

https://github.com/hazelcast/hazelcast-mono/blob/08c06833a3d6e7ab3b715ca8b55207e6d965dd84/hazelcast/hazelcast/src/main/java/com/hazelcast/map/impl/operation/PartitionWideEntryOperation.java#L222-L227
is not correctly handled when expiration is used. `operateOnKey`
internally invokes `RecordStore.get` which may mutate the record store
being iterated if the entry has just expired (note that it checks for
expiration again, using later timestamp than `RecordStore.forEach`).

This leads to missing execution on some entries and exceptions in logs
like the following one:

```
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.hazelcast.internal.locksupport.LockStoreImpl.isLocked(LockStoreImpl.java:113)
	at com.hazelcast.internal.locksupport.LockStoreProxy.isLocked(LockStoreProxy.java:78)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.isLocked(DefaultRecordStore.java:474)
	at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.hasExpired(AbstractEvictableRecordStore.java:137)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:359)
	at com.hazelcast.map.impl.recordstore.EnterpriseRecordStore.forEach(EnterpriseRecordStore.java:172)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:336)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:330)
	at com.hazelcast.map.impl.operation.PartitionWideEntryOperation.runWithPartitionScanForNative(PartitionWideEntryOperation.java:200)
	at com.hazelcast.map.impl.operation.PartitionWideEntryOperation.runForNative(PartitionWideEntryOperation.java:143)
	at com.hazelcast.map.impl.operation.PartitionWideEntryOperation.runInternal(PartitionWideEntryOperation.java:119)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:208)
	at com.hazelcast.map.impl.operation.MapOperation.call(MapOperation.java:227)
```

The operation usually does not fail because in case of such exception it
is retried.

Only entry processor invocations that scan the record store are
affected. Variants with single key or multiple explicit keys are not
affected.

On-heap IMaps seem to be unaffected, likely thank to better behavior of
iteration during removal of entry pointed to by the iterator from
collection. This case is not correctly handled for BEHM iterator.
`shiftConflictingKey` may replace entry being pointed to by the iterator
(iterator remembers slot for next entry) with null entry, leading to the
problems.

Example failure:
https://jenkins.hazelcast.com/job/Hazelcast-mono-pr-custom-tests-patryk/99/

The fix has the following elements:

1. ensure that mutating methods for HD RecordStore are not invoked
during iteration via assertions
2. do not invoke eviction (indirectly via `get`) after record was
obtained from iterator
3. the new method is used for entry processor only on HD IMap. It
_could_ also be used for on-heap IMaps.

This change might also increase the performance somewhat by avoiding
some extra work in `get`.

Fixes https://hazelcast.atlassian.net/browse/HZG-479

GitOrigin-RevId: 1063746f1505fc89a53e98b943e0230573258ae8