No need to check size vy using `keySet` method,  it may cause `java.lang.NoSuchMethodError: java/util/concurrent/ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView` when code is compiled under java 1.8 and run under 1.6/1.7