Wait for the invalidation event sent during the put operation before testing for the invalidation of entry expiry [CTT-982] (#5921)
Need to wait for the invalidation event sent during the put operation
before testing for the invalidation of entry expiry. Otherwise the
following scenario was causing random failures:

- We do get the entry and it is in local near cache.
- Near cache entry gets invalidated due to the invalidation sent for the
`replicatedMap.put`
- At the assert eventually loop we do get the entry again at the check
`assertNull(replicatedMap.get(1));` and re-populate the near cache.
- we get the expired entry event EVICTED from the map and this triggers
the second invalidations, hence, we end up the invalidation count as 2.

The reported failure was:
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapTest.lambda$testNearCacheInvalidationOnExpiry$4(ClientReplicatedMapTest.java:634)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1204)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1309)
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapTest.testNearCacheInvalidationOnExpiry(ClientReplicatedMapTest.java:630)
```

The solution was to wait and consume the first invalidation before
proceeding the test.

GitOrigin-RevId: a5b813fcf2fbb1853eef7230c7ee2e533ebde229