Hadoop image dependancies [CTT-662] (#5337)
jira - https://hazelcast.atlassian.net/browse/CTT-662
github - https://github.com/hazelcast/hazelcast-mono/issues/5082

Jackson Version Conflict:
```
Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.JsonAutoDetect$Value com.fasterxml.jackson.annotation.JsonAutoDetect$Value.construct(com.fasterxml.jackson.annotation.JsonAutoDetect$Visibility, com.fasterxml.jackson.annotation.JsonAutoDetect$Visibility, com.fasterxml.jackson.annotation.JsonAutoDetect$Visibility, com.fasterxml.jackson.annotation.JsonAutoDetect$Visibility, com.fasterxml.jackson.annotation.JsonAutoDetect$Visibility, com.fasterxml.jackson.annotation.JsonAutoDetect$Visibility)'
```
Cause:
The Hadoop distribution includes an older Jackson version.

Solution:
Removed the Jackson libraries bundled with Hadoop and replaced them with
a newer version.

Missing Dependencies:

https://jenkins.hazelcast.com/job/Hazelcast-mono-pr-custom-tests-using-docker/136/testReport/junit/com.hazelcast.jet.files/HdfsHadoopClasspathFilesTest/shouldReadParquetFile/
->
```
java.lang.NoClassDefFoundError: org/locationtech/jts/io/ParseException
```

https://jenkins.hazelcast.com/job/Hazelcast-mono-pr-custom-tests-using-docker/143/testReport/com.hazelcast.jet.files/HdfsHadoopClasspathFilesTest/shouldReadParquetFile/
->
```
Caused by: java.lang.NoClassDefFoundError: org/apache/parquet/variant/VariantConverters$ParentConverter
```
Solution:
Manually added the missing libraries (locationtech-jts and
parquet-variant) to the dependencies.

Checklist:

- [x] Labels (`Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `All Languages Should Check` set if making changes to the
Java client API and it may effect non-Java clients. Setting this label
will auto generate associated issues in all non-Java clients.
- [x] Architecture Design Record (ADR) reviewed and signed-off if this
PR represents a significant architectural change
- [x] Request reviewers if possible
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc
- [x] Send backports/forwardports if fix needs to be applied to
past/future releases

GitOrigin-RevId: 429e72f8e779f434ce0e370f6f778e46faf0b4d3