Fix Javadoc build caused by conflicting dependencies [DI-830] (#6942)
EE and OS both have Debezium extensions that use different versions of
the Debezium dependency.

We are getting [deploy
failures](https://jenkins.hazelcast.com/job/deploy-builds/job/Hazelcast-EE-master-javadoc-deploy/1502/)
because the wrong Debezium dependency is being resolved:
> [ERROR] Failed to execute goal
org.apache.maven.plugins:maven-javadoc-plugin:3.12.0:aggregate
(default-cli) on project hazelcast-enterprise-root: An error has
occurred in Javadoc report generation:
[ERROR] Exit code: 1
[ERROR]
/home/jenkins/jenkins_slave/workspace/deploy-builds/Hazelcast-EE-master-javadoc-deploy/hazelcast-enterprise-extensions/hazelcast-enterprise-cdc-debezium/src/main/java/com/hazelcast/enterprise/jet/cdc/impl/ReadCdcP.java:60:
error: cannot find symbol [ERROR] import static
io.debezium.relational.HistorizedRelationalDatabaseConnectorConfig.SCHEMA_HISTORY;
[ERROR] ^
[ERROR]   symbol:   static SCHEMA_HISTORY
[ERROR]   location: class HistorizedRelationalDatabaseConnectorConfig

When generating EE Javadoc, we run a single `javadoc:aggregate` command
that uses _all_ of the dependencies of the project.

Specifically, the `enterprise-it` module has a dependency on the (OS)
`hazelcast-distribution` - whose transitive dependencies include the OS
Debezium connector and thus dependency. This causes both old and new
versions of the dependency to end up on the classpath, leading to
compilation errors.
As those modules are using the `zip` distribution, these dependencies
are already bundled - and so they should not resolve the transitive
dependencies, as we do elsewhere.

Moreover, even if it wasn't for build stability issues - those
dependencies are not required for execution, so we can filter them out
to prevent them needing to be resolved to improve build performance.

I am unsure why this is a problem _now_ - I suspect this was always a
problem, but by fluke the ordering of the dependencies worked in our
favour, and by _touching_ the distribution in
https://github.com/hazelcast/hazelcast-mono/pull/6851 that's exposed
this issue.

[Example
execution](https://github.com/hazelcast/hazelcast-mono/actions/runs/26949983770/job/79512599897)
(showing successful build only, rest is WIP).

GitOrigin-RevId: 3a365b5a510981536575cb81cce7d56917d18b03