Remove killing connection from WriteJdbcPTest [HZ-1869] (#23091) [5.2.z]
We kill all the connections while using static instance with a shared
datastore. This datastore contains the connection pool with the
connections we kill which results with failures like:
```
java.lang.AssertionError: pgStatement.getConnection().getAutoCommit() should not throw
```
Killing only hides the problem of leaking connections, we should rather
try to find the holes.

Also changed the format of active connections to be tabular alike

Fixes https://github.com/hazelcast/hazelcast/issues/23061
Fixes https://hazelcast.atlassian.net/browse/HZ-1869

(cherry picked from commit d7bda2e92e12448106dc7544a0c6a61f36cd16d9)