Fixed NoClassDefFoundError in Windows test runs
Windows test runs fail with a java.lang.NoClassDefFoundError:
Could not initialize class org.fusesource.jansi.WindowsAnsiOutputStream

This can be fixed by configuring log4j with -Dlog4j.skipJansi

(cherry picked from commit bbe9ea8)