Supply global Maven configuration to address `Could not acquire read lock` [DI-306] (#3454)
In https://github.com/hazelcast/hazelcast-mono/pull/3452, the [Jenkins
OS PR builder was
failing](https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-pr-builder-v2/5200)
with:
```
java.lang.IllegalStateException: Could not acquire lock(s)
    at org.eclipse.aether.internal.impl.synccontext.named.NamedLockFactoryAdapter$AdaptedLockSyncContext.acquire (NamedLockFactoryAdapter.java:219)
{...}
Suppressed: java.lang.IllegalStateException: Attempt 1: Could not acquire read lock for 'artifact:com.fasterxml.jackson.core:jackson-annotations:2.18.0' in 30 SECONDS
```

The GitHub Actions PR builder was unaffected.

This [looks to be a timeout
issue](https://issues.apache.org/jira/browse/MNG-7868) where if artifact
resolution takes >30 seconds (default), it fails.

I _suspect_ that because
https://github.com/hazelcast/hazelcast-mono/pull/3452 made artifact
resolution more effecient, more could be done in parallel (because the
build is multithreaded), overloading the Jenkins runner, leading to
longer _individual_ artifact resolution times - going over the timeout.

We _already_ work around this in other parts of the PR builder by
increasing the timeout using the
[aether.syncContext.named.time](https://maven.apache.org/resolver/maven-resolver-impl/synccontextfactory.html#configuration-options-for-%E2%80%9Cnamed%E2%80%9D-synccontextfactory)
property.

The [OS PR builder was fixed by adding this configuration to the other
parts of the PR
builder](https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-pr-builder-v2/jobConfigHistory/showDiffFiles?timestamp1=2024-06-18_19-03-40&timestamp2=2024-10-17_19-30-07),
but [additional Jenkins jobs are failing with the same
issue](https://jenkins.hazelcast.com/job/deploy-builds/job/Hazelcast-javadoc-generated-checker/985).

Instead, we should move this configuration into
[jvm.config](https://maven.apache.org/configure.html#mvn-jvm-config-file)
to apply to all builds.

Because we still need to support building older versions of the
codebase, I cannot remove this configuration from the Jenkins jobs - but
I can from the GitHub Actions PR builder because they are versioned
together (🙌).

To test, [created an _additional_ copy of the OS PR builder _without_
the `aether.syncContext.named.time` workaround I added and ran there to
check it's still
passing](https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-pr-builder-v2-Jack/1).

GitOrigin-RevId: 4222c9bcb40f8bd56671d5bfda855408c5a3ac10