Fix flaky test failure for PostgreGenericMapStoreIT, PostgresGenericMapStoreSimpleIT [CTT-1002][CTT-1003] (#6016)
The test was dropping the table before stopping the Jet job. If the job
was still running, it continued executing `DELETE` statements. Postgres
then returned `org.postgresql.util.PSQLException: ERROR: relation
"postgre_testclear" does not exist` and jet retried indefinitely for
`testClear`, causing the test to hang.
To fix it, ditch the jobs before dropping table.

```
java.sql.BatchUpdateException: Batch entry 0 DELETE FROM "postgre_testclear" WHERE "id" = ('9518'::int4) OR "id" = ('5739'::int4) OR ("id" = ('3804'::int4) OR ("id" = ('4533'::int4) OR "id" = ('7198'::int4))) OR ("id" = ('4145'::int4) OR "id" = ('9942'::int4) OR ("id" = ('2370'::int4) OR ("id" = ('8562'::int4) OR "id" = ('3217'::int4)))) OR ("id" = ('2434'::int4) OR "id" = ('5722'::int4) OR ("id" = ('5284'::int4) OR ("id" = ('2774'::int4) OR "id" = ('7110'::int4))) OR ("id" = ('3499'::int4) OR "id" = ('9584'::int4) OR ("id" = ('2257'::int4) OR ("id" = ('6222'::int4) OR "id" = ('3538'::int4))))) OR ("id" = ('8963'::int4) OR "id" = ('9277'::int4) OR ("id" = ('8756'::int4) OR ("id" = ('1987'::int4) OR "id" = ('802'::int4))) OR ("id" = ('3276'::int4) OR "id" = ('9852'::int4) OR ("id" = ('9054'::int4) OR ("id" = ('3619'::int4) OR "id" = ('8231'::int4)))) OR ("id" = ('5518'::int4) OR "id" = ('9004'::int4) OR ("id" = ('6595'::int4) OR ("id" = ('2292'::int4) OR "id" = ('295'::int4))) OR ("id" = ('8214'::int4) OR ("id" = ('8446'::int4) OR "id" = ('6833'::int4)) OR ("id" = ('3906'::int4) OR ("id" = ('7740'::int4) OR "id" = ('1614'::int4)))))) was aborted: ERROR: relation "postgre_testclear" does not exist
...
Caused by: org.postgresql.util.PSQLException: ERROR: relation "postgre_testclear" does not exist
```

Checklist:

- [X] Labels (`Type:`, `Source:`, `Module:`) and Milestone set
- [X] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Label `All Languages Should Check` set if making changes to the
Java client API and it may effect non-Java clients. Setting this label
will auto generate associated issues in all non-Java clients.
- [ ] Architecture Design Record (ADR) reviewed and signed-off if this
PR represents a significant architectural change
- [X] Request reviewers if possible
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc
- [ ] Send backports/forwardports if fix needs to be applied to
past/future releases

GitOrigin-RevId: db23f454b3732ac02e51eeef9d3d43e12db998ce