Fix `os-pr.yaml` file reference (#7091)
The change in https://github.com/hazelcast/hazelcast-mono/pull/7015
[broke the workflow by referencing the wrong
path](https://github.com/hazelcast/hazelcast/actions/runs/28110718569/job/83237070316):
> Error: [copybara] 2: Error in the configuration, flags values or in
general an error attributable to the user. Check the logs for details.

GitOrigin-RevId: 4cfe9c02becdfe4c4d561ebf5ae5e86b50ad7fc5