Fix hanging `modulepath-tests` after CP -> EE migration [HZ-4652][HZ-4672] (#1352)
When [CP functionality was migrated from OS to
EE](https://github.com/hazelcast/hazelcast-mono/pull/1178), references
to the migrated classes were left in OS `META-INF`.

Because of this, when the `modulepath-tests` were executed, the
following error was logged:
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for /home/jenkins/jenkins_slave/workspace/Hazelcast-master-RedHatJDK21-Jack-HZ-4672/hazelcast/hazelcast/target/hazelcast-5.5.0-SNAPSHOT.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class com.hazelcast.cp.event.impl.CpEventDataSerializerHook not in JAR file hazelcast-5.5.0-SNAPSHOT.jar
```

Can reproduce locally by running the `modulepath-tests`:
```
./mvnw clean test --file hazelcast/modulepath-tests/pom.xml
```

In addition, following this error, Java hangs, leading to:
```
Build timed out (after 300 minutes). Marking the build as failed.
```
This appears to be a behaviour across multiple JDKs that I don't
understand, but is not the root cause of our issue so have not
addressed.

Changes:
- Move references to EE classes from OS to EE `META-INF`
- [Remove Maven `--debug` argument, added to investigate this
issue](https://github.com/hazelcast/hazelcast-mono/pull/1325)

Fixes:
- https://github.com/hazelcast/hazelcast/issues/26304
- https://github.com/hazelcast/hazelcast/issues/26306
- [HZ-4652](https://hazelcast.atlassian.net/browse/HZ-4652)
- [HZ-4672](https://hazelcast.atlassian.net/browse/HZ-4672)

[HZ-4652]:
https://hazelcast.atlassian.net/browse/HZ-4652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GitOrigin-RevId: 078dd919faf529cb0e9aa9c30f44c0a59ecff930