Add `serialVersionUID` to Jet classes (#4718)
A [test failure](https://hazelcast.atlassian.net/browse/HZC-7080) was
logged with an exception of:
```
java.io.InvalidClassException: com.hazelcast.jet.impl.processor.MetaSupplierFromProcessorSupplier; local class incompatible: stream classdesc serialVersionUID = -8763360639642351949, local class serialVersionUID = -7527314947445942512
```

[The root
cause](https://hazelcast.slack.com/archives/C09473XSLN5/p1753473977915239?thread_ts=1753460369.360029&cid=C09473XSLN5)
of this error was that some Jet classes are `Serializable`, but don't
declare `serialVersionUID`s - as such the generated UID was used instead
which is highly Java-implementation-dependent - and different versions
were (probably) compiled with different implementations of Java.

The failing test is _actually_ irrelevant [as we don't support any kind
of compatibility version range for
Jet](https://hazelcast.slack.com/archives/C034YQBTG/p1721326062424229)
(i.e. must all be on the same version), but that's a poor justification
for omitting the `serialVersionUID` because patch releases do seem to
have matching UIDs between them, despite _not_ being guaranteed
compatible so this error would not occur.

Changes:
- updated test that asserted the existence of a `serialVersionUID` for
Jet classes to catch the ones missed
- added _explicit_ `serialVersionUID`'s
- typically set to a default of `1L` as per
https://github.com/hazelcast/hazelcast/pull/19534
- but for a [special
case](https://github.com/hazelcast/hazelcast-mono/pull/4718#discussion_r2251949794),
set to the existing `5.5.0` value extracted via
`ObjectStreamClass.lookup(Class.forName("com.hazelcast.theclass")).getSerialVersionUID()`

Note - this also cleans up an IDE warning.

GitOrigin-RevId: a5968a65948f5710f8e9386483c7eaf039d81b32