Avoid logging errors for metricsJournal reads with a wrong sequence [MC-1177] (#22698)
Logs like:
```
Error reading from metrics journal, sequence: 716
java.lang.IllegalArgumentException: sequence:716 is too large. The current tail is:23
```
may occur when member was restarted and `metricsJournal` was recreated,
but MC tries to get metrics from the latest known sequence.
This case is gracefully handled on MC side, so MC retries reading
metrics with a sequence = 0.

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [x] Send backports/forwardports if fix needs to be applied to
past/future releases